"""Offline, node-locked license verification.

The app embeds only the Ed25519 *public* key (keys/license_pub.pem); the private
key stays with the vendor and never ships. Verification is fully offline: check
the signature, that the license's machine fingerprint matches this host, and that
it has not expired. Grace-period / lockdown policy is applied by the caller
(enforcement layer), not here.

License token format (single copy-pasteable string):
    RTD-LIC.v1.<base64url(payload_json)>.<base64url(ed25519_signature)>
"""
from __future__ import annotations

import base64
import hashlib
import json
import os
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

from cryptography.exceptions import InvalidSignature
from cryptography.hazmat.primitives.serialization import load_pem_public_key
from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PublicKey

TOKEN_PREFIX = "RTD-LIC.v1."
SCHEMA_VERSION = 1

# Days after expiry during which the app keeps running (soft-lock grace window).
GRACE_DAYS = 7

# If the system clock is ever this many hours behind the last-seen high-water
# mark, treat it as a rollback attempt to defeat expiry and lock down.
CLOCK_ROLLBACK_TOLERANCE_HOURS = 1

# Salt mixed into the raw host identifier before hashing. Not a secret (it ships
# in the image); it only makes the emitted fingerprint opaque and fixed-length.
FINGERPRINT_SALT = "rtd-license-v1"

_DEFAULT_PUBLIC_KEY_PATH = Path(__file__).resolve().parent.parent / "keys" / "license_pub.pem"


def _public_key_path() -> Path:
    """Public key location; overridable via RTD_LICENSE_PUBKEY (key rotation / tests)."""
    return Path(os.environ.get("RTD_LICENSE_PUBKEY", _DEFAULT_PUBLIC_KEY_PATH))

# Host-identifier ladder (see issue #2 design note). Each entry is (source_tag, path).
# The first readable, non-degenerate value wins. `dmi:` is strongest but root-only;
# `mid:` is world-readable. Installer-side capture writes host.fingerprint to avoid
# in-container permission issues; that file takes precedence over the raw ladder.
_LADDER = [
    ("dmi", "/sys/class/dmi/id/product_uuid"),
    ("mid", "/etc/machine-id"),
    ("mid", "/var/lib/dbus/machine-id"),
]

# product_uuid values that hypervisors hand out by default / all-zero — not unique.
_BOGUS_IDS = {
    "",
    "00000000-0000-0000-0000-000000000000",
    "ffffffff-ffff-ffff-ffff-ffffffffffff",
    "03000200-0400-0500-0006-000700080009",
}


class LicenseError(Exception):
    """Raised when a token is malformed or its signature is invalid (tampered/garbage)."""


@dataclass
class LicenseInfo:
    """A verified license payload plus the checks computed against this host/time."""
    license_id: str
    customer: str
    fingerprint: str
    issued_at: str
    expires_at: Optional[str]
    limits: dict = field(default_factory=dict)
    # Checks (filled by verify_license):
    fingerprint_ok: bool = False
    expired: bool = False
    in_grace: bool = False
    days_left: Optional[int] = None


# --- fingerprint -----------------------------------------------------------

def _read_raw_identifier() -> Optional[str]:
    """Return the raw 'source:value' host identifier, or None if none is available.

    Precedence: RTD_FINGERPRINT_SOURCE env (dev/test override) -> installer-written
    host.fingerprint file (RTD_DATA_DIR) -> the raw ladder.
    """
    override = os.environ.get("RTD_FINGERPRINT_SOURCE")
    if override:
        return override.strip()

    data_dir = os.environ.get("RTD_DATA_DIR")
    if data_dir:
        fp_file = Path(data_dir) / "host.fingerprint"
        if fp_file.is_file():
            text = fp_file.read_text(encoding="utf-8").strip()
            if text:
                return text

    for source, path in _LADDER:
        try:
            value = Path(path).read_text(encoding="utf-8").strip().lower()
        except (OSError, ValueError):
            continue
        if value and value not in _BOGUS_IDS:
            return f"{source}:{value}"
    return None


def compute_fingerprint() -> str:
    """Compute this host's fingerprint as 'source:hexhash'.

    Raises LicenseError if no usable host identifier is present (the `vol:` last
    resort is generated by the installer, not here).
    """
    raw = _read_raw_identifier()
    if not raw or ":" not in raw:
        raise LicenseError(
            "no usable machine identifier found (expected host.fingerprint, "
            "/sys/class/dmi/id/product_uuid, or /etc/machine-id)"
        )
    source, value = raw.split(":", 1)
    digest = hashlib.sha256(f"{FINGERPRINT_SALT}:{value}".encode("utf-8")).hexdigest()
    return f"{source}:{digest[:32]}"


# --- token codec -----------------------------------------------------------

def _b64u_decode(segment: str) -> bytes:
    padding = "=" * (-len(segment) % 4)
    return base64.urlsafe_b64decode(segment + padding)


def _split_token(token: str) -> tuple[str, bytes]:
    """Return (payload_segment, signature_bytes) or raise LicenseError."""
    token = token.strip()
    if not token.startswith(TOKEN_PREFIX):
        raise LicenseError("unrecognized license format")
    body = token[len(TOKEN_PREFIX):]
    parts = body.split(".")
    if len(parts) != 2:
        raise LicenseError("malformed license token")
    payload_segment, sig_segment = parts
    try:
        signature = _b64u_decode(sig_segment)
    except (ValueError, base64.binascii.Error) as exc:
        raise LicenseError("malformed license signature") from exc
    return payload_segment, signature


def _load_public_key() -> Ed25519PublicKey:
    path = _public_key_path()
    try:
        key = load_pem_public_key(path.read_bytes())
    except OSError as exc:
        raise LicenseError(f"license public key missing at {path}") from exc
    if not isinstance(key, Ed25519PublicKey):
        raise LicenseError("license public key is not an Ed25519 key")
    return key


# --- verification ----------------------------------------------------------

def _parse_dt(value: str) -> datetime:
    dt = datetime.fromisoformat(value)
    return dt if dt.tzinfo else dt.replace(tzinfo=timezone.utc)


def verify_license(
    token: str,
    fingerprint: Optional[str] = None,
    now: Optional[datetime] = None,
) -> LicenseInfo:
    """Verify a license token offline and return its info + host/time checks.

    Raises LicenseError on a malformed token or bad signature (hard-invalid).
    A fingerprint mismatch or expiry is reported via fields on the result, so the
    caller can apply grace-period / lockdown policy.
    """
    payload_segment, signature = _split_token(token)
    public_key = _load_public_key()
    try:
        public_key.verify(signature, payload_segment.encode("ascii"))
    except InvalidSignature as exc:
        raise LicenseError("license signature verification failed") from exc

    try:
        payload = json.loads(_b64u_decode(payload_segment))
    except (ValueError, base64.binascii.Error) as exc:
        raise LicenseError("license payload is not valid JSON") from exc

    if payload.get("schema_version") != SCHEMA_VERSION:
        raise LicenseError(f"unsupported license schema_version: {payload.get('schema_version')}")

    now = now or datetime.now(timezone.utc)
    if fingerprint is None:
        fingerprint = compute_fingerprint()

    expires_at = payload.get("expires_at")
    expired = False
    in_grace = False
    days_left = None
    if expires_at:
        exp = _parse_dt(expires_at)
        expired = now > exp
        days_left = (exp - now).days
        # Grace: expired, but within GRACE_DAYS of the expiry date.
        in_grace = expired and (now - exp).days < GRACE_DAYS

    return LicenseInfo(
        license_id=payload["license_id"],
        customer=payload["customer"],
        fingerprint=payload["fingerprint"],
        issued_at=payload["issued_at"],
        expires_at=expires_at,
        limits=payload.get("limits", {}),
        fingerprint_ok=(payload["fingerprint"] == fingerprint),
        expired=expired,
        in_grace=in_grace,
        days_left=days_left,
    )
